// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvC5heGJslJVIBJV83v219zbevCoS-3Rk',
    appId: '1:980292872070:web:ee1b56cdd1ec44a4cdee07',
    messagingSenderId: '980292872070',
    projectId: 'flutter-chat-app-8b388',
    authDomain: 'flutter-chat-app-8b388.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8b388.firebasestorage.app',
    measurementId: 'G-51RJWYGBSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJLTI66xZcXbZinnX04pOfA7zD0K9jaOk',
    appId: '1:980292872070:android:f5269f454fa67f48cdee07',
    messagingSenderId: '980292872070',
    projectId: 'flutter-chat-app-8b388',
    storageBucket: 'flutter-chat-app-8b388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWohLHAmFhy7tD-C4SqQBCxXWOhIyIsW4',
    appId: '1:980292872070:ios:ba36b4c9d6890329cdee07',
    messagingSenderId: '980292872070',
    projectId: 'flutter-chat-app-8b388',
    storageBucket: 'flutter-chat-app-8b388.firebasestorage.app',
    iosBundleId: 'com.example.p8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWohLHAmFhy7tD-C4SqQBCxXWOhIyIsW4',
    appId: '1:980292872070:ios:ba36b4c9d6890329cdee07',
    messagingSenderId: '980292872070',
    projectId: 'flutter-chat-app-8b388',
    storageBucket: 'flutter-chat-app-8b388.firebasestorage.app',
    iosBundleId: 'com.example.p8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvC5heGJslJVIBJV83v219zbevCoS-3Rk',
    appId: '1:980292872070:web:72c9e509bc8efffacdee07',
    messagingSenderId: '980292872070',
    projectId: 'flutter-chat-app-8b388',
    authDomain: 'flutter-chat-app-8b388.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8b388.firebasestorage.app',
    measurementId: 'G-X99N1T4F64',
  );

}